#!/usr/bin/perl

#   Sinn: Commandline-Pocketcalculator
#  Autor: t3o 2023++

# DONE change the parser to read char by char in a mode like "number" or "string"
# DONE we need types of things on the stack
# TODO inv
# TODO ^
# TODO do we need 3 over (ovr) ? or "<n> copy"?
# DONE: Parser ändern, dass er zeichenweise liest, dabei in einem Modus wie zb "zahl" ist, oder "string"
# DONE brauchen (eigentlich) Typen für Dinge auf dem Stack (das koennte ein Package sein)

# TODO: Programmierfähigkeit -- unter einem Namen eine zu parsende Zeichenkette ablegen
# TODO: Hilfe einbauen
# TODO konstanten
#
use constant REVISION => "20231213";

use strict;
use warnings;
use Data::Dumper;
use Getopt::Long;
use YAML::Syck;
use Test::More;
use Test::Exception;
use FindBin;
use lib "$FindBin::Bin";
use Parser;
use TheMachine;

$|=1;
$Data::Dumper::Sortkeys = 1;

GetOptions(
	'help|h' => \my $need_help,
	'nosave' => \my $nosave,         # default: false
	'noload' => \my $noload,         # default: false
	'statefile=s' => \my $statefile, # default: HOME/.rpnc
	# 'quiet'  => \my $be_quiet,
);
usage() if $need_help;

print "Welcome to the wunderful world of R-P-N-C\n";
my $rpnc = TheMachine->new(
	nosave => $nosave,
	noload => $noload,
	statefile => $statefile,
);
my $ops = $rpnc->operators();
push(@$ops, 'q');
my $pa = Parser->new( operators => $rpnc->operators() );
my $loop = 434;
while ($loop)
{
	$rpnc->show();
	my $input = <STDIN>;
	unless (defined $input) # Ctrl-d
	{
		print "\n";
		last;
	}
	chomp($input);

	my $atom;
	while(434)
	{
		my $thingy = $pa->next_atom( $input );
		$atom  = $thingy->[0];
		$input = $thingy->[1];
		# print " DEBUGGING atom from stream: " . Dumper($atom);
		my $type = $atom->{ type };
		last if $type eq Parser->END_OF_STREAM;
		if (($type eq Parser->OPERATOR) && ($atom->{value} eq "q")) # quit
		{
			$loop = 0;
			last;
		}
		else {
			$rpnc->do( $atom ); # handle NUMBER OPERATOR
		}
	}
}
$rpnc->shutdown();
exit(0);

# ----------------------------------------------------------------------------
sub usage
{
	my $msg = shift;
	print "$0 REVISION " . REVISION . "\n";
	print "ERROR: $msg\n" if defined $msg;
	print "Usage: $0 ....\n";
	exit(1);
}

